import type { ChatRoom, Message } from "@/types/chat-room"
import dayjs from '@/lib/dayjs'

const BASE_TIME = dayjs('2026-01-01 15:41')

export const chatRooms: ChatRoom[] = [
    {
      id: '1',
      name: 'astor.star',
      lastMessage: '이 채팅을 클릭해 주세요!',
      time: BASE_TIME,
      avatar: null,
      isSelfChat: true,
    },
    {
      id: '11',
      name: '공지',
      lastMessage: '나와의 채팅을 이용해주세요.',
      time: BASE_TIME,
      avatar: null,
      isSelfChat: false,
    },
    {
      id: '2',
      name: '2026 그룹공채 원 카카오 온보딩',
      lastMessage: '여러분~~~~ 내일 아침 10시, CEO와의 만남 시간에는...',
      time: BASE_TIME.subtract(2, 'hour').subtract(23, 'minute'), // 오후 1:18
      avatar: null,
      memberCount: 144,
    },
    {
      id: '3',
      name: '동기사랑 6조',
      lastMessage: 'Same here too',
      time: BASE_TIME.subtract(2, 'hour').subtract(31, 'minute'), // 오후 1:10
      avatar: null,
      memberCount: 8,
    },
    {
      id: '4',
      name: '페둥이들',
      lastMessage: 'ㄷㄷㄷ저희도 얼떨떨해요',
      time: BASE_TIME.subtract(3, 'hour').subtract(8, 'minute'), // 오후 12:33
      avatar: null,
      memberCount: 13,
    },
    {
      id: '5',
      name: '해커톤 22조',
      lastMessage: '#춘식도락메뉴 분석 챌린지 1. 2 번...',
      time: BASE_TIME.subtract(3, 'hour').subtract(18, 'minute'), // 오후 12:23
      avatar: null,
      memberCount: 4,
    },
  ]
  
export const chatMessages: Message[] = [
    {
      id: '2',
      roomId: '2',
      sender: 'olive',
      content: '여러분~~~~ 내일 아침 10시, CEO와의 만남 시간에는...',
      time: BASE_TIME.subtract(2, 'hour').subtract(23, 'minute'), // 오후 1:18
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },  
    {
      id: '3',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '식사 순서에 따라 다르지 않을까요?',
      time: BASE_TIME.subtract(2, 'hour').subtract(56, 'minute'), // 오후 12:45
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '4',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '여쭤보기가',
      time: BASE_TIME.subtract(2, 'hour').subtract(46, 'minute'), // 오후 12:55
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '5',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '애매한디요',
      time: BASE_TIME.subtract(2, 'hour').subtract(33, 'minute'), // 오후 1:08
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '6',
      roomId: '3',
      sender: '카카오페이 astor(김도훈)',
      content: '저희는 해커톤조끼리 먹어요',
      time: BASE_TIME.subtract(2, 'hour').subtract(32, 'minute'), // 오후 1:09
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '7',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: 'Same here',
      time: BASE_TIME.subtract(2, 'hour').subtract(31, 'minute'), // 오후 1:10
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '8',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: 'Same here too',
      time: BASE_TIME.subtract(2, 'hour').subtract(31, 'minute'), // 오후 1:10
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '9',
      roomId: '4',
      sender: '페둥이들',
      content: 'ㄷㄷㄷ저희도 얼떨떨해요',
      time: BASE_TIME.subtract(3, 'hour').subtract(8, 'minute'), // 오후 12:33
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '10',
      roomId: '5',
      sender: '해커톤 22조',
      content: '#춘식도락메뉴 분석 챌린지 1. 2 번...',
      time: BASE_TIME.subtract(3, 'hour').subtract(18, 'minute'), // 오후 12:23
      isMe: false,
      avatar: null,
      type: 'TEXT',
    },
    {
      id: '11',
      roomId: '1',
      sender: 'astor.star',
      content: '22조 화이팅~',
      time: BASE_TIME.add(9, 'day').add(1, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '12',
      roomId: '11',
      sender: '공지',
      content: '나와의 채팅을 이용해주세요.',
      time: BASE_TIME,
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    // 개인 메모 데이터 (20일 전부터 현재까지)
    {
      id: '14',
      roomId: '1',
      sender: 'astor.star',
      content: '새해 목표\n1. 운동 주 3회 이상\n2. 독서 월 2권\n3. 사이드 프로젝트 완성\n4. 건강검진 받기',
      time: BASE_TIME.subtract(20, 'day').subtract(2, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '15',
      roomId: '1',
      sender: 'astor.star',
      content: '장보기 리스트\n- 우유\n- 계란\n- 양파\n- 토마토\n- 닭가슴살',
      time: BASE_TIME.subtract(19, 'day').subtract(5, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '16',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      time: BASE_TIME.subtract(19, 'day').subtract(3, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '17',
      roomId: '1',
      sender: 'astor.star',
      content: '맛집 메모: 강남역 근처 이탈리안 레스토랑 "라 쿠치나"\n파스타 진짜 맛있음 👍\n예약 필수!',
      time: BASE_TIME.subtract(18, 'day').subtract(7, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '18',
      roomId: '1',
      sender: 'astor.star',
      content: '2026_해외여행_계획.pdf',
      time: BASE_TIME.subtract(18, 'day').subtract(4, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '19',
      roomId: '1',
      sender: 'astor.star',
      content: '아이디어: 일정 관리 앱에 AI 추천 기능 추가\n사용자의 습관 패턴 분석해서 최적의 일정 제안',
      time: BASE_TIME.subtract(17, 'day').subtract(9, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '20',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800',
      time: BASE_TIME.subtract(17, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',  
      avatar: null,
    },
    {
      id: '21',
      roomId: '1',
      sender: 'astor.star',
      content: '📚 읽을 책 리스트\n- 클린 코드\n- 실용주의 프로그래머\n- 객체지향의 사실과 오해\n- 도메인 주도 설계',
      time: BASE_TIME.subtract(16, 'day').subtract(8, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '22',
      roomId: '1',
      sender: 'astor.star',
      content: '블록체인_기초_개념.pdf',
      time: BASE_TIME.subtract(16, 'day').subtract(3, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '23',
      roomId: '1',
      sender: 'astor.star',
      content: '회의록 - 2026.01.15\n주제: Q1 목표 설정\n참석자: 팀 전원\n\n결정사항:\n- 신규 기능 3개 개발\n- 성능 개선 작업\n- 리팩토링 진행',
      time: BASE_TIME.subtract(15, 'day').subtract(5, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '24',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
      time: BASE_TIME.subtract(15, 'day').subtract(1, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '25',
      roomId: '1',
      sender: 'astor.star',
      content: '💡 "완벽을 추구하지 말고, 먼저 시작하라. 시작하면 길이 보인다."',
      time: BASE_TIME.subtract(14, 'day').subtract(10, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '26',
      roomId: '1',
      sender: 'astor.star',
      content: '운동 기록\n- 런닝 5km (30분)\n- 복근 운동 20분\n- 스트레칭 10분',
      time: BASE_TIME.subtract(14, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '27',
      roomId: '1',
      sender: 'astor.star',
      content: 'React_성능_최적화_방법.pdf',
      time: BASE_TIME.subtract(13, 'day').subtract(7, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '28',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800',
      time: BASE_TIME.subtract(13, 'day').subtract(4, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '29',
      roomId: '1',
      sender: 'astor.star',
      content: '프로젝트 TODO\n[ ] API 연동\n[ ] 로그인 페이지 디자인\n[x] 데이터베이스 설계\n[ ] 테스트 코드 작성',
      time: BASE_TIME.subtract(12, 'day').subtract(9, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '30',
      roomId: '1',
      sender: 'astor.star',
      content: '제주도 여행 체크리스트\n✓ 항공권 예약\n✓ 렌트카 예약\n- 숙소 예약\n- 맛집 리스트업',
      time: BASE_TIME.subtract(12, 'day').subtract(3, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '31',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
      time: BASE_TIME.subtract(11, 'day').subtract(8, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '32',
      roomId: '1',
      sender: 'astor.star',
      content: 'TypeScript_고급_패턴.pdf',
      time: BASE_TIME.subtract(11, 'day').subtract(5, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '33',
      roomId: '1',
      sender: 'astor.star',
      content: '아침 루틴\n6:30 - 기상\n7:00 - 운동\n8:00 - 샤워\n8:30 - 아침식사\n9:00 - 출근',
      time: BASE_TIME.subtract(10, 'day').subtract(7, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '34',
      roomId: '1',
      sender: 'astor.star',
      content: '오늘의 감사 3가지\n1. 따뜻한 햇살\n2. 맛있는 점심\n3. 동료들과의 좋은 대화',
      time: BASE_TIME.subtract(10, 'day').subtract(2, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '35',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1551963831-b3b1ca40c98e?w=800',
      time: BASE_TIME.subtract(9, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '36',
      roomId: '1',
      sender: 'astor.star',
      content: '버킷리스트 2026\n- 마라톤 완주\n- 제주 올레길 완주\n- 새로운 언어 배우기\n- 봉사활동 참여',
      time: BASE_TIME.subtract(9, 'day').subtract(4, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '37',
      roomId: '1',
      sender: 'astor.star',
      content: '월간_지출_내역_2026_01.xlsx',
      time: BASE_TIME.subtract(8, 'day').subtract(9, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '38',
      roomId: '1',
      sender: 'astor.star',
      content: '영화 보고 싶은 것\n- 듄2\n- 웡카\n- 오펜하이머\n- 킹덤 오브 더 플래닛',
      time: BASE_TIME.subtract(8, 'day').subtract(5, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '39',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      time: BASE_TIME.subtract(7, 'day').subtract(8, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '40',
      roomId: '1',
      sender: 'astor.star',
      content: '주말 계획\n토요일:\n- 아침 운동\n- 집 청소\n- 친구 만나기\n\n일요일:\n- 독서\n- 영화 보기\n- 요리 도전',
      time: BASE_TIME.subtract(7, 'day').subtract(3, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '41',
      roomId: '1',
      sender: 'astor.star',
      content: 'Next.js_14_새로운_기능.pdf',
      time: BASE_TIME.subtract(6, 'day').subtract(10, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '42',
      roomId: '1',
      sender: 'astor.star',
      content: '코딩 공부 계획\n1주차: 알고리즘 기초\n2주차: 자료구조 복습\n3주차: 디자인 패턴\n4주차: 프로젝트 실습',
      time: BASE_TIME.subtract(6, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '43',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
      time: BASE_TIME.subtract(5, 'day').subtract(7, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '44',
      roomId: '1',
      sender: 'astor.star',
      content: '💪 운동 목표\n- 체중 5kg 감량\n- 벤치프레스 100kg\n- 데드리프트 150kg\n- 풀업 20개',
      time: BASE_TIME.subtract(5, 'day').subtract(4, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '45',
      roomId: '1',
      sender: 'astor.star',
      content: '카페 추천 리스트\n1. 성수 - 어니언\n2. 한남 - 프릳츠\n3. 익선동 - 식물\n4. 망원 - 테라로사',
      time: BASE_TIME.subtract(4, 'day').subtract(9, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '46',
      roomId: '1',
      sender: 'astor.star',
      content: '블록체인_기초_개념.pdf',
      time: BASE_TIME.subtract(4, 'day').subtract(5, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '47',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
      time: BASE_TIME.subtract(3, 'day').subtract(8, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '48',
      roomId: '1',
      sender: 'astor.star',
      content: '🎯 이번 주 목표\n- 프로젝트 진도 30% 완성\n- 운동 3회\n- 책 1권 완독\n- 영어 공부 매일 30분',
      time: BASE_TIME.subtract(3, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '49',
      roomId: '1',
      sender: 'astor.star',
      content: '선물 아이디어\n엄마 - 안마의자\n아빠 - 골프채\n동생 - 에어팟 프로\n친구 - 향수',
      time: BASE_TIME.subtract(2, 'day').subtract(10, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '50',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800',
      time: BASE_TIME.subtract(2, 'day').subtract(7, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '51',
      roomId: '1',
      sender: 'astor.star',
      content: 'AI_트렌드_2026.pptx',
      time: BASE_TIME.subtract(2, 'day').subtract(4, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '52',
      roomId: '1',
      sender: 'astor.star',
      content: '명언 모음\n"실패는 성공의 어머니"\n"천 리 길도 한 걸음부터"\n"시작이 반이다"',
      time: BASE_TIME.subtract(1, 'day').subtract(9, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '53',
      roomId: '1',
      sender: 'astor.star',
      content: '다이어트 식단\n아침: 그릭요거트 + 과일\n점심: 닭가슴살 샐러드\n저녁: 현미밥 + 생선구이',
      time: BASE_TIME.subtract(1, 'day').subtract(6, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '54',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
      time: BASE_TIME.subtract(1, 'day').subtract(3, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '55',
      roomId: '1',
      sender: 'astor.star',
      content: '오늘 배운 것\n- React useCallback 최적화\n- TypeScript 제네릭 활용\n- CSS Grid 레이아웃',
      time: BASE_TIME.subtract(12, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '56',
      roomId: '1',
      sender: 'astor.star',
      content: '개발자_취업_가이드.pdf',
      time: BASE_TIME.subtract(10, 'hour'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '57',
      roomId: '1',
      sender: 'astor.star',
      content: '기억할 것\n- 매일 감사하기\n- 작은 성공 축하하기\n- 실패 두려워하지 않기\n- 꾸준히 노력하기',
      time: BASE_TIME.subtract(8, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '58',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800',
      time: BASE_TIME.subtract(6, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '59',
      roomId: '1',
      sender: 'astor.star',
      content: '⚡ Quick Note\nAPI 엔드포인트: /api/v1/users\n인증 방식: Bearer Token\n응답 형식: JSON',
      time: BASE_TIME.subtract(4, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '60',
      roomId: '1',
      sender: 'astor.star',
      content: '이번 달 독서 목표\n✓ 클린 코드 (완독)\n□ 리팩토링 2판\n□ 실용주의 프로그래머',
      time: BASE_TIME.subtract(2, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '61',
      roomId: '1',
      sender: 'astor.star',
      content: 'Docker_컨테이너_가이드.pdf',
      time: BASE_TIME.subtract(1, 'hour').subtract(30, 'minute'),
      isMe: true,
      type: 'DOCUMENT',
      avatar: null,
    },
    {
      id: '62',
      roomId: '1',
      sender: 'astor.star',
      content: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800',
      time: BASE_TIME.subtract(1, 'hour'),
      isMe: true,
      type: 'IMAGE_VIDEO',
      avatar: null,
    },
    {
      id: '63',
      roomId: '1',
      sender: 'astor.star',
      content: '🎨 디자인 영감\n- Dribbble\n- Behance\n- Pinterest\n- Awwwards',
      time: BASE_TIME.subtract(45, 'minute'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '64',
      roomId: '1',
      sender: 'astor.star',
      content: '집중력 높이는 방법\n1. 휴대폰 멀리하기\n2. 25분 작업 + 5분 휴식\n3. 작업 환경 정리\n4. 충분한 수면',
      time: BASE_TIME.subtract(30, 'minute'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '65',
      roomId: '1',
      sender: 'astor.star',
      content: '오늘 할 일\n✓ 아침 운동\n✓ 프로젝트 작업\n□ 코드 리뷰\n□ 팀 미팅\n□ 저녁 약속',
      time: BASE_TIME.subtract(15, 'minute'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '1',
      roomId: '1',
      sender: '채팅봇',
      content: `📚 AI 톡서랍 사용 안내

🔧 사용 방법
우측 상단의 클라우드 버튼을 눌러 톡클라우드에 진입해주세요
드래그앤드롭, 붙여넣기, +버튼으로 파일을 업로드할 수 있어요

✨ 기능
[카테고리 분류]
파일을 업로드하면 AI가 카테고리를 자동으로 분류해요
[태그 추출]
파일을 업로드하면 AI가 태그를 자동으로 추출해요
[파일 요약]
파일을 업로드하면 AI가 요약을 자동으로 생성해요
[파일 검색]
파일의 내용, 특징을 입력해도 유사한 파일을 검색할 수 있어요

⚠️ 주의 사항
톡서랍을 제외한 다른 데이터/UI는 카카오톡을 가상으로 흉내낸 것이며 실제로 동작하지 않아요`,
      time: BASE_TIME.add(10, 'day'),
      isMe: false,
      type: 'TEXT',
      avatar: null,
    },
    {
      id: '13',
      roomId: '1',
      sender: 'astor.star',
      content: `🚨🚨🚨 잠시만요! 🚨🚨🚨
      
프로토타입이라 로그인 기능이 없어요.
파일을 올리면 모든 유저가 같이 보게 되니, 민감한 파일은 올리지 않도록 주의해 주세요!
`,
      time: BASE_TIME.add(10, 'day').add(1, 'hour'),
      isMe: true,
      type: 'TEXT',
      avatar: null,
    },
  ]
