import type { ChatRoom, Message } from "@/types/chat-room"

export const chatRooms: ChatRoom[] = [
    {
      id: '1',
      name: '김도훈',
      lastMessage: '테스트',
      time: '오후 3:41',
      avatar: null,
      isSelfChat: true,
    },
    {
      id: '2',
      name: '2026 그룹공채 원 카카오 온보딩',
      lastMessage: '여러분~~~~ 내일 아침 10시, CEO와의 만남 시간에는...',
      time: '오후 1:18',
      avatar: null,
      memberCount: 144,
    },
    {
      id: '3',
      name: '동기사랑 6조',
      lastMessage: 'Same here too',
      time: '오후 1:10',
      avatar: null,
      memberCount: 8,
    },
    {
      id: '4',
      name: '페둥이들',
      lastMessage: 'ㄷㄷㄷ저희도 얼떨떨해요',
      time: '오후 12:33',
      avatar: null,
      memberCount: 13,
    },
    {
      id: '5',
      name: '해커톤 22조',
      lastMessage: '#춘식도락메뉴 분석 챌린지 1. 2 번...',
      time: '오후 12:23',
      avatar: null,
      memberCount: 4,
    },
  ]
  
export const chatMessages: Message[] = [
    {
      id: '1',
      roomId: '1',
      sender: '김도훈',
      content: '테스트',
      time: '오후 3:41',
      isMe: true,
      avatar: null,
    },
    {
      id: '2',
      roomId: '2',
      sender: 'olive',
      content: '여러분~~~~ 내일 아침 10시, CEO와의 만남 시간에는...',
      time: '오후 1:18',
      isMe: false,
      avatar: null,
    },  
    {
      id: '3',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '식사 순서에 따라 다르지 않을까요?',
      time: '오후 12:45',
      isMe: false,
      avatar: null,
    },
    {
      id: '4',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '여쭤보기가',
      time: '오후 12:55',
      isMe: false,
      avatar: null,
    },
    {
      id: '5',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: '애매한디요',
      time: '오후 1:08',
      isMe: false,
      avatar: null,
    },
    {
      id: '6',
      roomId: '3',
      sender: '카카오페이 astor(김도훈)',
      content: '저희는 해커톤조끼리 먹어요',
      time: '오후 1:09',
      isMe: true,
      avatar: null,
    },
    {
      id: '7',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: 'Same here',
      time: '오후 1:10',
      isMe: false,
      avatar: null,
    },
    {
      id: '8',
      roomId: '3',
      sender: '카카오게임즈 james(한승준)',
      content: 'Same here too',
      time: '오후 1:10',
      isMe: false,
      avatar: null,
    },
    {
      id: '9',
      roomId: '4',
      sender: '페둥이들',
      content: 'ㄷㄷㄷ저희도 얼떨떨해요',
      time: '오후 12:33',
      isMe: false,
      avatar: null,
    },
    {
      id: '10',
      roomId: '5',
      sender: '해커톤 22조',
      content: '#춘식도락메뉴 분석 챌린지 1. 2 번...',
      time: '오후 12:23',
      isMe: false,
      avatar: null,
    },
]
