import type { FileItem } from '@/types/file'
import dayjs from '@/lib/dayjs'

export const mockFiles: FileItem[] = [
  {
    id: 1,
    fileOverview: '네트워크 프로토콜 패킷 분석 과제 제출 자료',
    fileType: 'document',
    originalFileName: 'TCP:UDP 패킷 분석_2020130885_김도....pdf',
    savedFileName: '2769510',
    tags: [
      { id: 1, description: '서류', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 2, description: '과제', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['카카오'],
    createdAt: dayjs('2025-09-26'),
    modifiedAt: dayjs('2025-09-26'),
  },
  {
    id: 2,
    fileOverview: 'KPMG 한국 모바일 결제 시장 분석 보고서',
    fileType: 'document',
    originalFileName: 'kpmg-korea-mobile-payments-20231113.pdf',
    savedFileName: '20283392',
    tags: [
      { id: 3, description: '업무', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 4, description: '리포트', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['업무'],
    createdAt: dayjs('2025-09-03'),
    modifiedAt: dayjs('2025-09-03'),
  },
  {
    id: 3,
    fileOverview: 'SK 스토어 데이터 분석 스크립트',
    fileType: 'etc',
    originalFileName: 'sk-store-analyzer.cjs',
    savedFileName: '8334',
    tags: [
      { id: 5, description: '코드', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 6, description: '분석', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['프로젝트'],
    createdAt: dayjs('2025-09-03'),
    modifiedAt: dayjs('2025-09-03'),
  },
  {
    id: 4,
    fileOverview: 'SK 스토어 분석 결과 데이터',
    fileType: 'document',
    originalFileName: 'sk-store-analysis.csv',
    savedFileName: '180879',
    tags: [
      { id: 7, description: '데이터', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 8, description: '분석', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['프로젝트'],
    createdAt: dayjs('2025-09-03'),
    modifiedAt: dayjs('2025-09-03'),
  },
  {
    id: 5,
    fileOverview: 'API 응답 결과 JSON 데이터',
    fileType: 'etc',
    originalFileName: 'response.json',
    savedFileName: '6029312',
    tags: [
      { id: 9, description: '개발', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['개발'],
    createdAt: dayjs('2025-09-03'),
    modifiedAt: dayjs('2025-09-03'),
  },
  {
    id: 6,
    fileOverview: '대학 리스트 문서',
    fileType: 'document',
    originalFileName: '202507_대학리스트.docx',
    savedFileName: '1048576',
    tags: [
      { id: 10, description: '문서', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 11, description: '학교', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['교육'],
    createdAt: dayjs('2025-07-15'),
    modifiedAt: dayjs('2025-07-15'),
  },
  {
    id: 7,
    fileOverview: '여행 사진',
    fileType: 'image',
    originalFileName: '20260107_132040-1.jpg',
    savedFileName: '21209088',
    tags: [
      { id: 12, description: '사진', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 13, description: '여행', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['추억'],
    createdAt: dayjs('2026-01-07'),
    modifiedAt: dayjs('2026-01-07'),
  },
  {
    id: 8,
    fileOverview: '대학 리스트 스프레드시트',
    fileType: 'document',
    originalFileName: '202507_대학리스트.xlsx',
    savedFileName: '2097152',
    tags: [
      { id: 14, description: '문서', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 15, description: '학교', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['교육'],
    createdAt: dayjs('2025-07-15'),
    modifiedAt: dayjs('2025-07-15'),
  },
  {
    id: 9,
    fileOverview: '추억 사진',
    fileType: 'image',
    originalFileName: '20260107_132040-2.jpg',
    savedFileName: '16562380',
    tags: [
      { id: 16, description: '사진', createdAt: dayjs(), modifiedAt: dayjs() },
      { id: 17, description: '추억', createdAt: dayjs(), modifiedAt: dayjs() },
    ],
    categories: ['추억'],
    createdAt: dayjs('2026-01-07'),
    modifiedAt: dayjs('2026-01-07'),
  },
]
